### ISSUE TITLE
Remove (or update) textures

### ISSUE THREAD

**Issue by crsaracco** [crsaracco/critterding#8]
I liked the way the old critterding looked, without the new textures.

Either update them to look a little better (If you ever read this Sam Porter... sorry!) or just remove them.

Might be able to remove the Qt dependency if you do this?

NOTE: I'm not sure if this affects the critters' vision-related stuff though.

**Comment by ethicalfive** [comment]
As im not really a great artist, I did the best I could, just change the textures yourself..?

The point of adding textures was to give them something better then solid colors to stare at. Also the textures are made for the critters point of view rather then the users, most of the work was put into making sure the textures were high resolution up close, not really in how they look from a distance to the user.

Just edit the .mtl files and you can set solid colors and remove the textures there if thats what you prefer.

**Comment by crsaracco** [comment]
Haha holy crap - I didn't expect the artist to read this!

> The point of adding textures was to give them something better then solid colors to stare at. 

Yep, I figured that might be the case. If it affects how they might evolve, then I would rather keep them in because it adds yet another element to the evolution.

> Just edit the .mtl files and you can set solid colors and remove the textures there if thats what you prefer.

Would that have the effect of the critters seeing the textures but the user not? I might look into it if so.

-----

I kinda put this fork on the back-burner a little bit because life's been super busy, but I've been meaning to get back into it. I see you have some repos related to critterding on your GitHub -- is there a more active repo that I didn't know about that I could contribute to instead?

**Comment by ethicalfive** [comment]
> Haha holy crap - I didn't expect the artist to read this!
> 
The programmer for the project discovered it today, so I had a read through! 

> > The point of adding textures was to give them something better then solid colors to stare at.
> 
> Yep, I figured that might be the case. If it affects how they might evolve, then I would rather keep them in because it adds yet another element to the evolution.
> 
> > Just edit the .mtl files and you can set solid colors and remove the textures there if thats what you prefer.
> 
> Would that have the effect of the critters seeing the textures but the user not? I might look into it if so. Maybe make a keybinding for show/hide textures (I forget at the moment if that's already a thing?)
> 
Yep, it would definitely effect what the critters see, they see what you see, each critter retina is rendered with a camera the same as the viewport camera. Although what they "see" is relative. To be fair the vast majority of critters i've evolved over the years don't really develop anything I would call eyesight, even though they have they retina inputs available to them. I've seen a critter from an earlier version (pre physics fix) that 100% reacted to seeing other critters and food and im fairly sure during our distributed simulation (spanning over 4 pcs) those critters seemed to be aware of the things around them.
> I kinda put this fork on the back-burner a little bit because life's been super busy, but I've been meaning to get back into it. I see you have some repos related to critterding on your GitHub -- is there a more active repo that I didn't know about that I could contribute to instead?

There is two projects in development, my fork of critterding called critterthing, although I haven't pushed my changes onto github yet, It adds a bunch of maps and textures, UI improvements like text entry boxes, a new fitness function mode based off the --race 1 mode, added some random and pulse inputs to the brains, saving and loading the current profile with your critters and a bunch of bug fixes. If you have an interest, I can prioritise doing it. Here is a dl of it if you're curious https://drive.google.com/open?id=1QzGQchXIaVb6dWBPAXtd_Y4B3E0oNwvg

The other project is critterding2, it was closed source but Bob is currently in the process of opening the source. Its really more of a game engine which supports alife. 

Feel free to hop onto IRC - freenode #critterding if you ever want to chat directly with us.

**Comment by crsaracco** [comment]
> Yep, it would definitely effect what the critters see, they see what you see, each critter retina is rendered with a camera the same as the viewport camera.

Ah ok. I assume that means even if I had a feature to turn on/off the textures via hotkey, that would also change what they saw. In that case, I think I'll leave the textures as they are (at least for now), so I'll close this issue.

> Although what they "see" is relative. To be fair the vast majority of critters i've evolved over the years don't really develop anything I would call eyesight, even though they have they retina inputs available to them.

From what I can tell in the current version, it seems like it's pretty common for critters to start trying to navigate themselves towards food. Some of them try to keep the food in sight, at the very least. It takes a little while for them to get to that point though, like maybe a day or so.

> There is two projects in development, my fork of critterding called critterthing, although I haven't pushed my changes onto github yet, It adds a bunch of maps and textures, UI improvements like text entry boxes, a new fitness function mode based off the --race 1 mode, added some random and pulse inputs to the brains, saving and loading the current profile with your critters and a bunch of bug fixes. If you have an interest, I can prioritise doing it.

No rush, I'm still a bit busy for the next ~month (in the process of switching jobs at the moment). I'm definitely interested in general though, so I'll check in later!

My main goal for right now was to modernize the code a little bit -- in particular, I was working on removing some of the older boost stuff in favor of the new `std::` stuff. I could probably help with that if you're interested in that as well.

> Feel free to hop onto IRC - freenode #critterding if you ever want to chat directly with us.

Sounds good! I'll probably join in when I start working on the project a little more.

**Comment by crsaracco** [comment]
> Yep, it would definitely effect what the critters see, they see what you see, each critter retina is rendered with a camera the same as the viewport camera.

Ah ok. I assume that means even if I had a feature to turn on/off the textures via hotkey, that would also change what they saw. In that case, I think I'll leave the textures as they are (at least for now), so I'll close this issue.

> Although what they "see" is relative. To be fair the vast majority of critters i've evolved over the years don't really develop anything I would call eyesight, even though they have they retina inputs available to them.

From what I can tell in the current version, it seems like it's pretty common for critters to start trying to navigate themselves towards food. Some of them try to keep the food in sight, at the very least. It takes a little while for them to get to that point though, like maybe a day or so of simulation.

> There is two projects in development, my fork of critterding called critterthing, although I haven't pushed my changes onto github yet, It adds a bunch of maps and textures, UI improvements like text entry boxes, a new fitness function mode based off the --race 1 mode, added some random and pulse inputs to the brains, saving and loading the current profile with your critters and a bunch of bug fixes. If you have an interest, I can prioritise doing it.

No rush, I'm still a bit busy for the next ~month or so. I'm definitely interested in general though, so I'll check in later!

My main goal for right now was to modernize the code a little bit -- in particular, I was working on removing some of the older boost stuff in favor of the new `std::` stuff. I could probably help with that if you're interested in that as well.

> Feel free to hop onto IRC - freenode #critterding if you ever want to chat directly with us.

Sounds good! I'll probably join in when I start working on the project a little more.

**Comment by ethicalfive** [comment]
I just realise I gave you a very old version of critterthing, I've uploaded the lastest version onto github now and am in the process of migrating to qt5 :) Sorry about that old link!
